# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 15.0
org_name: Quartile Limited
org_slug: qrtl
rebel_module_groups: []
repo_description: ''
repo_name: SST CUSTOM
repo_slug: sst-custom
repo_website: https://www.quartile.co
use_pyproject_toml: false
use_ruff: false

